### PR TITLE
Increase maxResults property, retrieve projects for query from config file

### PR DESCRIPTION
**Pull request by The-Huginn**
Just a temporary solution, see more details in #61

### CODE REVIEW

**Review by xstefank — CHANGES_REQUESTED** [review]
@The-Huginn I don't understand why do we need this kind of temp solution? just fix the original issue.

**Comment by The-Huginn** [comment]
On the second thought, we have decided to move forward with a different approach, I will update this shortly

**Comment by The-Huginn** [comment]
- Due to mocking problem with tests and `@ApplicationScoped` on `@Command` I have created a bean, which in tests hold mocked class for context.
- Retrieve projects for search query directly from config file, and aggregate different collector beans into a single producer instead of static methods
-  Additionally resolves #64

**Review by xstefank — CHANGES_REQUESTED** [review]

**Comment by xstefank** [comment]
After the offline discussion, the points will be followed up. Merging.

**Pull request merged**
